apiVersion: apps/v1
kind: Deployment
metadata:
    name: capstone-deployment
    labels:
        app: capstone
spec:
    replicas: 2
    selector:
        matchLabels:
            app: capstone
    template:
        metadata:
            labels:
                app: capstone
        spec:
            containers:
            - name: capstone
              image: aberdean/capstone:v1
              ports:
              - containerPort: 80
    strategy:
        type: RollingUpdate
        maxUnavailable: 50%
        