apiVersion: apps/v1
kind: Deployment
metadata:
    name: capstone-deployment
    labels:
        app: capstone
spec:
    replicas: 4
    selector:
        matchLabels:
            app: capstone
    template:
        metadata:
            labels:
                app: capstone
        spec:
            containers:
            - name: capstone
              image: aberdean/capstone:v2
              ports:
              - containerPort: 80
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 25%
            maxSurge: 1
        